"""add created_by to company tables

Revision ID: 35d3cd1c6bff
Revises: 86f928adc872
Create Date: 2026-06-08 17:03:25.412844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d3cd1c6bff'
down_revision: Union[str, Sequence[str], None] = '86f928adc872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enroll_businesses', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enroll_businesses', 'user_table', ['created_by'], ['id'])
    op.add_column('word_of_mouth', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'word_of_mouth', 'user_table', ['created_by'], ['id'])
    op.add_column('yelp_companies', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'yelp_companies', 'user_table', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yelp_companies', type_='foreignkey')
    op.drop_column('yelp_companies', 'created_by')
    op.drop_constraint(None, 'word_of_mouth', type_='foreignkey')
    op.drop_column('word_of_mouth', 'created_by')
    op.drop_constraint(None, 'enroll_businesses', type_='foreignkey')
    op.drop_column('enroll_businesses', 'created_by')
    # ### end Alembic commands ###
