"""add role to user_table

Revision ID: 86f928adc872
Revises: 
Create Date: 2026-06-08 16:51:23.369923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f928adc872'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_enroll_businesses_id'), 'enroll_businesses', ['id'], unique=False)
    op.add_column('user_table', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_word_of_mouth_id'), 'word_of_mouth', ['id'], unique=False)
    op.create_index(op.f('ix_yelp_companies_id'), 'yelp_companies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yelp_companies_id'), table_name='yelp_companies')
    op.drop_index(op.f('ix_word_of_mouth_id'), table_name='word_of_mouth')
    op.drop_column('user_table', 'role')
    op.drop_index(op.f('ix_enroll_businesses_id'), table_name='enroll_businesses')
    # ### end Alembic commands ###
